server:
    port: 18080

mybatis-plus:
  type-aliases-package: com.zzq.pro.entity
  mapper-locations: classpath:mapper/**/*.xml
  global-config:
    id-type: 0  #0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
    logic-delete-value: 0
    logic-not-delete-value: 1
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: false
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    #config-location: classpath:mybatis/mybatis-config.xml

spring:
  datasource:
    druid:
    #DruidDataSource 所需参数
      master:
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

      slave:
        url: jdbc:mysql://localhost:3306/testtest
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver


#    filters: stat,wall
#    maxActive: 20
#    initialSize: 5
#    maxWait: 60000
#    minIdle: 10
#    #maxIdle: 15
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 from dual
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: false
#    maxPoolPreparedStatementPerConnectionSize: 20
#    removeAbandoned: true
#    removeAbandonedTimeout: 1800
#    logAbandoned: true
#    connectionProperties:  druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=3000
#    useGlobalDataSourceStat: true
#    # Druid 监控 Servlet 配置参数
#    druidRegistrationUrl: /druid/*
#    resetEnable: true
#    loginUsername: 8zairDev
#    loginPassword: 123456
#    # Druid 监控过滤相关配置参数
#    filtersUrlPatterns: /*
#    exclusions: '*.js,*.gif,*.jpg,*.jpeg,*.png,*.css,*.ico,*.jsp,/druid/*'
#    sessionStatMaxCount: 2000
#    sessionStatEnable: true
#    principalSessionName: session_user_key
#    profileEnable: true